# Generated by Django 5.1.3 on 2024-11-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepoData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='etag',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='repository',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('user', 'repository_name'), name='unique_user_repository'),
        ),
    ]
